import { Restaurant, Address, Order, User } from '../types';

export const MOCK_USER: User = {
  id: 'usr_1',
  email: 'alex.smith@example.com',
  phone: '+1 (555) 019-2834',
  firstName: 'Alex',
  lastName: 'Smith',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
};

export const MOCK_ADDRESSES: Address[] = [
  {
    id: 'adr_1',
    title: 'Home',
    addressLine1: '128 Orchard St',
    addressLine2: 'Apt 4B',
    city: 'New York',
    state: 'NY',
    postalCode: '10002',
    country: 'USA',
    latitude: 40.7203,
    longitude: -73.9892,
    isDefault: true,
  },
  {
    id: 'adr_2',
    title: 'Office',
    addressLine1: '350 5th Ave',
    addressLine2: 'Floor 64',
    city: 'New York',
    state: 'NY',
    postalCode: '10118',
    country: 'USA',
    latitude: 40.7484,
    longitude: -73.9857,
    isDefault: false,
  },
];

export const MOCK_CATEGORIES = [
  { id: 'cat_1', name: 'Pizza', icon: '🍕' },
  { id: 'cat_2', name: 'Burgers', icon: '🍔' },
  { id: 'cat_3', name: 'Sushi', icon: '🍣' },
  { id: 'cat_4', name: 'Salads', icon: '🥗' },
  { id: 'cat_5', name: 'Desserts', icon: '🍰' },
  { id: 'cat_6', name: 'Drinks', icon: '🥤' },
  { id: 'cat_7', name: 'Asian', icon: '🍜' },
  { id: 'cat_8', name: 'Mexican', icon: '🌮' },
];

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: 'res_1',
    name: 'Tavern & Pizzeria',
    description: 'Neapolitan style wood-fired pizzas with artisanal toppings.',
    address: '84 Rivington St, New York, NY 10002',
    latitude: 40.7209,
    longitude: -73.9881,
    logoUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=150&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
    phoneNumber: '+1 (555) 234-5678',
    rating: 4.8,
    reviewCount: 342,
    isFeatured: true,
    deliveryRadiusKm: 4.0,
    minOrderAmount: 15.00,
    baseDeliveryFee: 2.99,
    prepTimeRange: '15-25 min',
    categories: ['Pizza', 'Italian'],
    foodItems: [
      {
        id: 'food_1',
        restaurantId: 'res_1',
        name: 'Margherita Pizza',
        description: 'San Marzano tomatoes, fresh mozzarella, fresh basil, and extra virgin olive oil.',
        price: 14.99,
        imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isEgg: false,
        isNonVeg: false,
        isAvailable: true,
        rating: 4.9,
        variants: [
          { id: 'v_1', name: 'Personal 10"', price: 14.99, isAvailable: true },
          { id: 'v_2', name: 'Large 14"', price: 19.99, isAvailable: true },
        ],
        addonGroups: [
          {
            id: 'ag_1',
            name: 'Extra Toppings',
            minSelections: 0,
            maxSelections: 4,
            isRequired: false,
            items: [
              { id: 'add_1', name: 'Pepperoni', price: 2.00, isAvailable: true },
              { id: 'add_2', name: 'Mushrooms', price: 1.50, isAvailable: true },
              { id: 'add_3', name: 'Extra Cheese', price: 2.50, isAvailable: true },
              { id: 'add_4', name: 'Truffle Oil', price: 3.00, isAvailable: true },
            ],
          },
        ],
      },
      {
        id: 'food_2',
        restaurantId: 'res_1',
        name: 'Truffle Mushroom Pizza',
        description: 'Wild forest mushrooms, white truffle oil, fresh rosemary, and creamy fontina.',
        price: 18.50,
        imageUrl: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isEgg: false,
        isNonVeg: false,
        isAvailable: true,
        rating: 4.7,
      },
    ],
  },
  {
    id: 'res_2',
    name: 'Burger & Co.',
    description: 'Juicy craft burgers cooked to order with signature hand-cut fries.',
    address: '156 Ludlow St, New York, NY 10002',
    latitude: 40.7201,
    longitude: -73.9877,
    logoUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=150&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    phoneNumber: '+1 (555) 345-6789',
    rating: 4.6,
    reviewCount: 512,
    isFeatured: true,
    deliveryRadiusKm: 3.5,
    minOrderAmount: 10.00,
    baseDeliveryFee: 1.99,
    prepTimeRange: '20-30 min',
    categories: ['Burgers', 'American'],
    foodItems: [
      {
        id: 'food_3',
        restaurantId: 'res_2',
        name: 'Classic Cheeseburger',
        description: 'Prime Angus beef patty, cheddar, lettuce, tomato, pickles, and house sauce on brioche.',
        price: 12.99,
        imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=400&q=80',
        isVeg: false,
        isEgg: false,
        isNonVeg: true,
        isAvailable: true,
        rating: 4.8,
        variants: [
          { id: 'v_3', name: 'Single Patty', price: 12.99, isAvailable: true },
          { id: 'v_4', name: 'Double Patty', price: 15.99, isAvailable: true },
        ],
        addonGroups: [
          {
            id: 'ag_2',
            name: 'Add-ons',
            minSelections: 0,
            maxSelections: 3,
            isRequired: false,
            items: [
              { id: 'add_5', name: 'Crispy Bacon', price: 2.00, isAvailable: true },
              { id: 'add_6', name: 'Fried Egg', price: 1.50, isAvailable: true },
              { id: 'add_7', name: 'Avocado', price: 2.00, isAvailable: true },
            ],
          },
        ],
      },
    ],
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord_1',
    restaurant: {
      id: 'res_1',
      name: 'Tavern & Pizzeria',
      logoUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=150&q=80',
    },
    items: [
      {
        name: 'Margherita Pizza',
        price: 14.99,
        quantity: 1,
        variantName: 'Personal 10"',
        addons: ['Pepperoni'],
      },
    ],
    status: 'DELIVERED',
    subtotal: 16.99,
    deliveryFee: 2.99,
    taxAmount: 1.50,
    totalAmount: 21.48,
    createdAt: '2026-07-02T12:00:00Z',
  },
  {
    id: 'ord_2',
    restaurant: {
      id: 'res_2',
      name: 'Burger & Co.',
      logoUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=150&q=80',
    },
    items: [
      {
        name: 'Classic Cheeseburger',
        price: 12.99,
        quantity: 2,
        variantName: 'Double Patty',
        addons: ['Crispy Bacon'],
      },
    ],
    status: 'PREPARING',
    subtotal: 35.98,
    deliveryFee: 1.99,
    taxAmount: 3.20,
    totalAmount: 41.17,
    createdAt: '2026-07-02T18:00:00Z',
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 'nt_1',
    title: 'Order Delivered!',
    body: 'Your order from Tavern & Pizzeria has been delivered. Enjoy!',
    type: 'ORDER_STATUS',
    createdAt: '10 min ago',
    isRead: false,
  },
  {
    id: 'nt_2',
    title: '50% Off Special Promo',
    body: 'Use coupon code EATS50 to get 50% off on your next order.',
    type: 'PROMO',
    createdAt: '2 hours ago',
    isRead: true,
  },
];
